load("@@//build_external/breakpad:breakpad_generate_config_header.bzl", "breakpad_generate_config_header")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

breakpad_generate_config_header(
    name = "config_h",
    src = "src/config.h.in",
    out = "src/config.h",
)

cc_library(
    name = "loose_headers",
    hdrs = [
        "src/client/linux/dump_writer_common/mapping_info.h",
        "src/client/linux/dump_writer_common/raw_context_cpu.h",
        "src/client/linux/handler/microdump_extra_info.h",
        "src/client/linux/minidump_writer/pe_structs.h",
        "src/common/android/include/elf.h",
        "src/common/android/include/link.h",
        "src/common/android/include/sys/user.h",
        "src/common/android/testing/mkdtemp.h",
        "src/common/dwarf/dwarf2enums.h",
        "src/common/dwarf/line_state_machine.h",
        "src/common/dwarf/types.h",
        "src/common/tests/auto_tempdir.h",
        "src/google_breakpad/processor/code_module.h",
        "src/google_breakpad/processor/code_modules.h",
        "src/google_breakpad/processor/exception_record.h",
        "src/google_breakpad/processor/memory_region.h",
        "src/google_breakpad/processor/system_info.h",
        "src/tools/linux/md2core/minidump_memory_range.h",
    ] + glob([
        "src/common/*.h",
        "src/processor/*.h",
        "src/google_breakpad/common/*.h",
        "src/third_party/curl/*.h",
        "src/common/linux/*.h",
    ]),
    visibility = ["//visibility:private"],
)

cc_library(
    name = "libbreakpad_client",
    srcs = [
        "src/client/linux/crash_generation/crash_generation_client.cc",
        "src/client/linux/crash_generation/crash_generation_client.h",
        "src/client/linux/dump_writer_common/thread_info.cc",
        "src/client/linux/dump_writer_common/thread_info.h",
        "src/client/linux/dump_writer_common/ucontext_reader.cc",
        "src/client/linux/dump_writer_common/ucontext_reader.h",
        "src/client/linux/handler/exception_handler.cc",
        "src/client/linux/handler/minidump_descriptor.cc",
        "src/client/linux/log/log.cc",
        "src/client/linux/log/log.h",
        "src/client/linux/microdump_writer/microdump_writer.cc",
        "src/client/linux/minidump_writer/linux_core_dumper.cc",
        "src/client/linux/minidump_writer/linux_dumper.cc",
        "src/client/linux/minidump_writer/linux_ptrace_dumper.cc",
        "src/client/linux/minidump_writer/minidump_writer.cc",
        "src/client/linux/minidump_writer/pe_file.cc",
        "src/client/minidump_file_writer.cc",
        "src/client/minidump_file_writer.h",
        "src/client/minidump_file_writer-inl.h",
        "src/common/convert_UTF.cc",
        "src/common/convert_UTF.h",
        "src/common/linux/breakpad_getcontext.S",
        "src/common/linux/elf_core_dump.cc",
        "src/common/linux/elf_core_dump.h",
        "src/common/linux/elfutils.cc",
        "src/common/linux/elfutils.h",
        "src/common/linux/elfutils-inl.h",
        "src/common/linux/file_id.cc",
        "src/common/linux/guid_creator.cc",
        "src/common/linux/guid_creator.h",
        "src/common/linux/linux_libc_support.cc",
        "src/common/linux/memory_mapped_file.cc",
        "src/common/linux/safe_readlink.cc",
        "src/common/md5.cc",
        "src/common/md5.h",
        "src/common/path_helper.cc",
        "src/common/path_helper.h",
        "src/common/string_conversion.cc",
        "src/common/string_conversion.h",
        "src/google_breakpad/processor/dump_context.h",
        "src/google_breakpad/processor/dump_object.h",
        "src/google_breakpad/processor/microdump.h",
        "src/google_breakpad/processor/proc_maps_linux.h",
        "src/processor/basic_code_modules.cc",
        "src/processor/basic_code_modules.h",
        "src/processor/convert_old_arm64_context.cc",
        "src/processor/dump_context.cc",
        "src/processor/dump_object.cc",
        "src/processor/logging.cc",
        "src/processor/logging.h",
        "src/processor/microdump.cc",
        "src/processor/minidump.cc",
        "src/processor/pathname_stripper.cc",
        "src/processor/pathname_stripper.h",
        "src/processor/proc_maps_linux.cc",
        "src/processor/range_map-inl.h",
        ":config_h",
    ],
    hdrs = [
        "src/client/linux/handler/exception_handler.h",
        "src/client/linux/handler/minidump_descriptor.h",
        "src/client/linux/microdump_writer/microdump_writer.h",
        "src/client/linux/minidump_writer/cpu_set.h",
        "src/client/linux/minidump_writer/directory_reader.h",
        "src/client/linux/minidump_writer/line_reader.h",
        "src/client/linux/minidump_writer/linux_core_dumper.h",
        "src/client/linux/minidump_writer/linux_dumper.h",
        "src/client/linux/minidump_writer/linux_ptrace_dumper.h",
        "src/client/linux/minidump_writer/minidump_writer.h",
        "src/client/linux/minidump_writer/pe_file.h",
        "src/client/linux/minidump_writer/proc_cpuinfo_reader.h",
        "src/common/linux/breakpad_getcontext.h",
        "src/common/linux/file_id.h",
        "src/common/linux/linux_libc_support.h",
        "src/common/linux/memory_mapped_file.h",
        "src/common/linux/safe_readlink.h",
        "src/google_breakpad/processor/minidump.h",
        "src/processor/convert_old_arm64_context.h",
    ],
    copts = ["-Wno-implicit-fallthrough"],
    includes = [
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":loose_headers",
        "@linux-syscall-support//:third_party_lss",
    ],
)
